Create DZ2.html
kvmpsk/DZ pull request #3
Opened 2021-02-23 08:45 UTC by kvmpsk

2021-02-24 20:04 UTC, kvmpsk commented
Домашнее задание №2

2021-02-25 15:05 UTC, Om1X requested changes

2021-02-25 15:05 UTC, Om1X commented on DZ2.html
> +			console.log(a + b);
здесь просто else

2021-02-25 15:05 UTC, Om1X commented on DZ2.html
> +				// вариант 2
это уже лишнее

2021-02-25 15:05 UTC, Om1X commented on DZ2.html
> +			}
не правильно, в задаче сказано

> С помощью оператора switch
У Вас же и функция и цикл

2021-02-25 15:05 UTC, Om1X commented on DZ2.html
> +		}
Ваша функция явно не завершена, на данный момент она возвращает функции и ничего не считает.

2021-02-25 15:05 UTC, Om1X commented on DZ2.html
> +			alert(deegree2(5));
> С **помощью рекурсии** организовать функцию возведения числа в степень.

2021-02-25 15:05 UTC, Om1X commented on DZ2.html
> +			alert(deegree2(5));
У вас просто функция которая перемножает число на само себя

2021-02-28 15:43 UTC, merged